import {StyleSheet} from 'react-native';

import {ms} from '../../utils/deviceConfig';
import {colors, fontSizes, fontWeights} from '../../theme';

export const styles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
  },
  container: {
    flex: 1,
    padding: ms(24),
  },
  header: {
    fontSize: fontSizes.huge,
    color: colors.white,
    fontFamily: 'serif',
    fontWeight: fontWeights.semiBold,
    marginBottom: ms(8),
  },
  subheader: {
    color: colors.gray,
    fontSize: fontSizes.md,
    marginBottom: ms(32),
    maxWidth: ms(400),
  },
  sectionTitle: {
    color: colors.white,
    fontFamily: 'serif',
    fontSize: fontSizes.xl,
    fontWeight: fontWeights.semiBold,
    marginBottom: ms(8),
  },
  guestsRow: {
    flexDirection: 'column',
    marginBottom: ms(8),
  },
  guestSliderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: ms(10),
  },
  guestCountContainer: {
    alignItems: 'center',
    marginBottom: ms(8),
  },
  guestCountText: {
    color: colors.white,
    fontSize: fontSizes.lg,
    fontFamily: 'serif',
    fontWeight: fontWeights.semiBold,
    left: -ms(10),
  },
  guestCountBubble: {
    position: 'absolute',
    left: ms(10),
    top: ms(10),
    width: ms(40),
    height: ms(30),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: ms(6),
    zIndex: 2,
  },
  sliderBarContainer: {
    flex: 1,
    alignItems: 'center',
  },
  sliderFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: ms(56),
    backgroundColor: colors.primaryTeal,
    borderRadius: ms(12),
    zIndex: 1,
    opacity: 0.7,
    justifyContent: 'flex-start',
  },
  sliderButton: {
    width: ms(28),
    height: ms(28),
    alignItems: 'center',
  },
  sliderButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  sliderButtonText: {
    color: colors.grayLighter,
    fontSize: fontSizes.lg,
    fontWeight: fontWeights.bold,
  },
  sliderBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceAlt,
    borderRadius: ms(8),
    borderWidth: 1,
    borderColor: colors.borderColor,
    height: ms(56),
  },
  sliderTick: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
  },
  sliderTickMark: {
    width: ms(1),
    height: ms(28),
    backgroundColor: colors.borderColor,
    marginBottom: ms(2),
    borderRadius: ms(1),
    alignSelf: 'flex-end',
  },
  sliderTickMarkSelected: {
    backgroundColor: colors.white,
    height: ms(22),
  },
  sliderTickLabel: {
    color: colors.borderColor,
    fontSize: fontSizes.sm,
    marginTop: ms(2),
    fontFamily: 'serif',
  },
  sliderTickLabelSelected: {
    color: colors.white,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.md,
  },
  sliderBarOverlay: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
    zIndex: 10,
  },
  sliderBarOverlayView: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
  },
  guestHint: {
    color: colors.grayMedium,
    fontSize: fontSizes.sm,
    marginBottom: ms(16),
    marginTop: ms(2),
  },
  bold: {fontWeight: fontWeights.bold, color: colors.white},
  italic: {fontStyle: 'italic'},
  unused: {color: colors.grayMedium},
  chargeRow: {
    flexDirection: 'row',
    marginBottom: ms(16),
    gap: ms(8),
  },
  chargeOption: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.borderColor,
    borderRadius: ms(8),
    padding: ms(14),
    marginRight: ms(8),
    backgroundColor: colors.surfaceAlt,
    minWidth: ms(120),
  },
  chargeOptionSelected: {
    borderColor: colors.white,
    backgroundColor: colors.optionSelected,
  },
  chargeOptionTitle: {
    color: colors.white,
    fontWeight: fontWeights.semiBold,
    fontSize: fontSizes.md,
    marginBottom: ms(2),
  },
  chargeOptionDesc: {
    color: colors.grayLighter,
    fontSize: fontSizes.sm,
  },
  tierRow: {
    marginBottom: ms(16),
  },
  tierOption: {
    borderWidth: 1,
    borderColor: colors.borderColor,
    borderRadius: ms(8),
    padding: ms(14),
    marginBottom: ms(10),
    backgroundColor: colors.surfaceAlt,
  },
  tierOptionSelected: {
    borderColor: colors.white,
    backgroundColor: colors.optionSelected,
  },
  tierOptionDisabled: {
    opacity: 0.4,
  },
  tierTitle: {
    color: colors.white,
    fontWeight: fontWeights.semiBold,
    fontSize: fontSizes.md,
    marginBottom: ms(2),
  },
  tierTitleDisabled: {
    color: colors.grayMedium,
    fontWeight: fontWeights.semiBold,
    fontSize: fontSizes.md,
    marginBottom: ms(2),
  },
  tierDesc: {
    color: colors.grayLighter,
    fontSize: fontSizes.sm,
  },
  tierDescDisabled: {
    color: colors.grayMedium,
    fontSize: fontSizes.sm,
  },
  tierPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: ms(2),
  },
  tierPrice: {
    color: colors.white,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.sm,
    marginLeft: ms(8),
  },
  subtotalRow: {
    flex: 1,
    alignItems: 'center',
    marginVertical: ms(16),
  },
  subtotalText: {
    color: colors.grayLighter,
    fontSize: fontSizes.md,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: ms(24),
    justifyContent: 'space-between',
  },
  backText: {
    color: colors.grayLighter,
    textDecorationLine: 'underline',
    fontSize: fontSizes.md,
  },
  nextButton: {
    backgroundColor: colors.infoExtraLight,
    borderRadius: ms(12),
    paddingVertical: ms(12),
    paddingHorizontal: ms(32),
    marginLeft: ms(8),
  },
  nextButtonText: {
    color: colors.grayDark,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.md,
    letterSpacing: 1,
  },
});
