import { QuestionCategory } from "./types";

export const QUESTION_CATEGORIES: QuestionCategory[] = [
  {
    key: 'SUGGESTED QUESTIONS',
    label: 'SUGGESTED QUESTIONS',
    questions: [
      "I break rules I don't agree with",
      'I find politically incorrect humor funny',
      'I love to engage in vigorous intellectual debates',
      'I would end a friendship over differing political views',
      "Conflict just isn't in my nature",
      'My partner can be friends with an ex',
      'I want a simple life',
      'I could live a happy life in solitude',
      'I consider myself to be "bookish"',
      'If you do nothing for an entire day, how do you feel?',
      'Expensive dates would be more fun',
      "It's best to split the bill on the first date",
      'Billionaires should not exist',
      'I have a 5-year plan',
      'I consider myself to be outdoorsy',
      'I go to great lengths to minimize my harm to the planet',
      'I pay attention to what I eat',
      'Exercising is an important part of my lifestyle',
      'I surround myself with people who appreciate the arts',
      "I'm willing to sacrifice comfort for style",
      'I enjoy PDA',
      'I generally like to take control during sex',
      "It's okay to date multiple people simultaneously",
      'I want children',
      'I want to start a family sooner rather than later',
      "It's important my kids be raised religious",
      "It's important my kids play musical instruments growing up",
      'Sports are an important part of family time',
      'It is important that my family lives abroad for some period of time',
      'The family unit is more important than the individual',
      'I am the definition of "the life of the party"',
    ],
  },
  {
    key: 'POPULAR',
    label: 'POPULAR',
    questions: [
      'I am the definition of "the life of the party"',
      "I break rules I don't agree with",
      'I want a simple life',
      'I would sacrifice stability to pursue a passion',
      'I find politically incorrect humor funny',
      'I would end a friendship over differing political views',
      'I would move somewhere where I don’t know anyone',
      'I have a 5-year plan',
      'Expensive dates would be more fun',
      "It's best to split the bill on the first date",
      'I pay attention to what I eat',
      'I could live a happy life in solitude',
      'If you do nothing for an entire day, how do you feel?',
      'Exercising is an important part of my lifestyle',
      'I consider myself to be outdoorsy',
      'I go to great lengths to minimize my harm to the planet',
      "I'm willing to sacrifice comfort for style",
      'I surround myself with people who appreciate the arts',
      "It's important my kids be raised religious",
      'I love to dance',
      'Sports are an important part of family time',
      'I am a competitive person',
      'I love to engage in vigorous intellectual debates',
      "Conflict just isn't in my nature",
      "It's okay to date multiple people simultaneously",
      'I generally like to take control during sex',
      'My partner can be friends with an ex',
      'My partner can go through my phone',
      "It's important to me that my parents approve of my partner",
      'I want to start a family sooner rather than later',
      'I want children',
    ],
  },
  {
    key: 'IMPORTANT',
    label: 'IMPORTANT',
    questions: [
      "It's important to me that everyone likes me",
      'I find politically incorrect humor funny',
      'I pay attention to what I eat',
      'I would try any drug at least once',
      'Exercising is an important part of my lifestyle',
      'Expensive dates would be more fun',
      'Traditional gender roles are important in relationships',
      "It's important to me that my parents approve of my partner",
      'I run most major decisions by my parents',
      'I would end a friendship over differing political views',
      'I distrust people by default',
      'My religion is the foundation of my moral compass',
      'I could live a happy life in solitude',
      'I believe in an afterlife',
      'I pray',
      'I am a workaholic',
      'I do whatever it takes to get ahead',
      'I define my success by the amount of money I make',
      "It's best to split the bill on the first date",
      'Billionaires should not exist',
      'I would sacrifice my personal life for my career goals',
      'I would sacrifice stability to pursue a passion',
      "It's okay to date multiple people simultaneously",
      'How long do you think is appropriate to wait before having sex?',
      'I generally like to take control during sex',
      'I want to start a family sooner rather than later',
      "I'd rather stay single forever than marry the wrong person",
      'The family unit is more important than the individual',
      'I want children',
      "It's important my kids be raised religious",
      "Children don't owe their parents anything",
      'I go to great lengths to minimize my harm to the planet',
    ],
  },
  {
    key: 'SPICY',
    label: 'SPICY',
    questions: [
      "I'm special",
      "I'd rule the world if I could",
      'I would accept a bribe',
      'I would shoplift',
      'I would try any drug at least once',
      'I like drama',
      'I find politically incorrect humor funny',
      'Some people should be bullied more',
      "It's okay to be mean if it's funny",
      'Nobody is better than anyone else',
      'I am sensitive to criticism',
      'I would always back my partner up publicly if they caused a scene',
      'Traditional gender roles are important in relationships',
      "It's best to split the bill on the first date",
      'Expensive dates would be more fun',
      'I can find it within myself to love someone if they’re rich enough',
      'How long do you think is appropriate to wait before having sex?',
      'I enjoy PDA',
      'Flirting is a form of cheating',
      "It's okay to date multiple people simultaneously",
      "I don't do hookups",
      'I would never bring a hookup home to an unmade bed',
      'I generally like to take control during sex',
      'I would have a threesome',
      'My partner can be friends with an ex',
      "I'd rather stay single forever than marry the wrong person",
    ],
  },
  {
    key: 'PROFESSIONAL',
    label: 'PROFESSIONAL',
    questions: [
      'I would sacrifice my personal life for my career goals',
      'I would sacrifice stability to pursue a passion',
      'Would you rather work a high-paying job that you hate or a low-paying job that you love?',
      'I define my success by the amount of money I make',
      'I want to leave a legacy',
      'I let other people take the lead',
      'Quitting is a sign of',
      'Being non-confrontational is a sign of weakness',
      'Criticism motivates me',
      'I take pride in my punctuality',
      "It's smart to expect the worst",
      'I am more concerned with results than processes',
      'My gut feeling is more reliable than my logical reasoning',
      'I always take the path with the lowest risk',
      "I'm a rule-breaker",
      'Small talk is a waste of time',
      'I actively cultivate my personal brand',
      'Big crowds are my',
      "At a social event, I'm usually the",
      'I avoid burning bridges at all costs',
      'I would quit my job if my long-term partner needed me to',
      'I prefer to communicate more',
      "I enjoy the thrill of not knowing what's ahead",
      'Your work colleagues can never be your true friends',
      'I am going to change the world',
    ],
  },
  {
    key: '40+',
    label: '40+',
    questions: [
      'I must travel extensively with my partner',
      "I'd rather cook my own meals than dine out",
      'Time apart is necessary for a healthy relationship',
      'I would quit my job if my long-term partner needed me to',
      'You can never truly fall out of love with someone',
      'My family is a big part of my identity',
      'Traditional gender roles are important in relationships',
      'I believe in marriage as an institution',
      "I'm open to being in a non-monogamous relationship",
      'I only date people I can see myself marrying',
      "I would tell a child Santa isn't real",
      'I only worry about things I can control',
      "I don't like holding onto things that remind me of the past",
      "I'm open to trying anything my partner asks me to try",
      "I should know all of my partner's sexual history",
      'The best parts of my life are still ahead of me',
      "I believe in people's ability to change",
      'Who should be the primary caregiver in the relationship?',
      'My partner and I should have completely separate finances',
      'Exercising is an important part of my lifestyle',
      'People should treat kids from past relationships as if they were their own',
      "I'm open to being in a relationship with someone who already has kids",
      'My health goals play a big role in how I live my daily life',
      "I'm open to moving in together with my partner",
      'The main draw of sex for me is more emotional than physical',
    ],
  },
  {
    key: 'RANDOM',
    label: 'RANDOM',
    questions: [
      'I need to be famous',
      "Children don't owe their parents anything",
      'My family is a big part of my identity',
      "It's attractive when someone plays hard to get",
      "I don't like to talk about my love life",
      "Conflict just isn't in my nature",
      "I'm open to being in a relationship with someone who already has kids",
      'The best things in life are free',
      'It’s ok that my match drinks',
      'Small talk is a waste of time',
      "I will only have sex if I'm in love",
      "It's important to me that everyone likes me",
      'I prefer to make the first move',
      'I enjoy being in the spotlight',
      "I don't like holding onto things that remind me of the past",
      'Saving for the future is more important than enjoying life today',
      'I run most major decisions by my parents',
      'I want to start a family sooner rather than later',
      'I prefer a minimalistic lifestyle',
      'Time apart is necessary for a healthy relationship',
      "I'm special",
      'I believe in marriage as an institution',
      'I believe I can truly change the world',
      "I should know all of my partner's sexual history",
      'I would help my partner cover up a murder',
      'I actively cultivate my personal brand',
      'I would sacrifice my personal life for my career goals',
      'It’s ok that my match smokes cigarettes',
      'I get up with my first alarm',
      "I break rules I don't agree with",
      'Society is too politically correct',
      "I'm willing to sacrifice comfort for style",
      'It’s okay to break promises sometimes',
      'I am the definition of "the life of the party"',
    ],
  },
];

export const premiumQuestions: string[] = ["I'm special"];

export  const TABS: string[] = [
  'SUGGESTED QUESTIONS',
  'POPULAR',
  'IMPORTANT',
  'SPICY',
  'PROFESSIONAL',
  '40+',
  'RANDOM',
];
