import {StyleSheet} from 'react-native';

import {ms} from '../../utils/deviceConfig';
import {colors, fontSizes, fontWeights} from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: ms(24),
    paddingHorizontal: ms(8),
  },
  header: {
    fontSize: fontSizes.huge,
    color: colors.white,
    fontFamily: 'serif',
    fontWeight: fontWeights.semiBold,
    alignSelf: 'center',
    marginBottom: ms(8),
  },
  subheader: {
    color: colors.grayLighter,
    fontSize: fontSizes.base,
    alignSelf: 'center',
    maxWidth: ms(400),
    textAlign: 'center',
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: ms(8),
    marginTop: ms(8),
  },
  tab: {
    paddingVertical: ms(8),
    paddingHorizontal: ms(18),
    borderRadius: ms(18),
    borderWidth: 1,
    borderColor: colors.borderColor,
    marginHorizontal: ms(4),
    backgroundColor: colors.transparent,
  },
  tabActive: {
    backgroundColor: colors.white,
    borderColor: colors.white,
  },
  tabText: {
    color: colors.grayLighter,
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.sm,
  },
  tabTextActive: {
    color: colors.surfaceAlt,
  },
  categoryRow: {
    flexGrow: 0,
    marginBottom: ms(8),
    marginTop: ms(4),
    maxHeight: ms(40),
  },
  categoryButton: {
    paddingVertical: ms(6),
    paddingHorizontal: ms(16),
    borderRadius: ms(16),
    marginRight: ms(8),
    borderWidth: 1,
    borderColor: colors.grayDark,
  },
  categoryButtonText: {
    color: colors.grayLighter,
    fontWeight: fontWeights.medium,
    fontSize: fontSizes.sm,
  },
  categoryButtonTextActive: {
    color: colors.surfaceAlt,
    fontWeight: fontWeights.bold,
  },
  columns: {
    flex: 1,
    marginTop: ms(8),
    marginBottom: ms(8),
  },
  column: {
    flex: 1,
    marginHorizontal: ms(4),
    marginBottom: ms(8),
  },
  colHeader: {
    color: colors.grayLighter,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.medium,
    marginBottom: ms(8),
    marginLeft: ms(4),
    letterSpacing: 1,
  },
  scrollCol: {
    backgroundColor: 'transparent',
    borderRadius: ms(12),
    borderWidth: 1,
    borderColor: colors.grayDark,
    padding: ms(4),
    minHeight: ms(120),
    maxHeight: ms(420),
  },
  card: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: ms(12),
    borderWidth: 1,
    borderColor: colors.borderColor,
    padding: ms(16),
    marginBottom: ms(10),
    minHeight: ms(56),
    justifyContent: 'center',
    marginRight: ms(10),
    marginTop: 0,
    width: '47%',
  },
  eventCard: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: ms(12),
    borderColor: colors.borderColor,
    padding: ms(8),
    marginBottom: ms(10),
    marginRight: ms(10),
    marginTop: 0,
    width: '100%',
  },
  cardAvailable: {
    borderStyle: 'dashed',
    borderColor: colors.borderColor,
  },
  cardSelected: {
    opacity: 0.5,
  },
  cardText: {
    color: colors.white,
    fontSize: fontSizes.md,
    fontWeight: fontWeights.medium,
  },
  premiumBadge: {
    position: 'absolute',
    right: ms(8),
    bottom: ms(8),
    backgroundColor: colors.grayDark,
    borderRadius: ms(4),
    paddingHorizontal: ms(6),
    paddingVertical: ms(2),
    borderWidth: 1,
    borderColor: colors.borderColor,
  },
  premiumText: {
    color: colors.grayLighter,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.bold,
    letterSpacing: 1,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: ms(8),
    marginBottom: ms(8),
    paddingHorizontal: ms(8),
  },
  backText: {
    color: colors.grayLighter,
    textDecorationLine: 'underline',
    fontSize: fontSizes.md,
  },
  nextButton: {
    backgroundColor: colors.infoExtraLight,
    borderRadius: ms(12),
    paddingVertical: ms(12),
    paddingHorizontal: ms(32),
  },
  nextButtonText: {
    color: colors.grayDark,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.md,
    letterSpacing: 1,
  },
  suggestedButtonDisabled: {
    backgroundColor: colors.borderColor,
    opacity: 0.5,
    borderColor: colors.borderColor,
  },
  suggestedButton: {
    borderWidth: 1,
    borderColor: colors.successAlt,
    borderRadius: ms(16),
    paddingVertical: ms(6),
    paddingHorizontal: ms(14),
    backgroundColor: colors.transparent,
    marginLeft: ms(6),
  },
  suggestedButtonText: {
    color: colors.white,
    fontWeight: fontWeights.bold,
    fontSize: fontSizes.sm,
    letterSpacing: 1,
  },
  emptyEventContainer: {
    paddingBottom: ms(16),
    flexGrow: 1,
    justifyContent: 'center',
  },
  emptyEventInner: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingTop: ms(32),
  },
  emptyEventText: {
    color: colors.grayMedium,
    fontSize: fontSizes.md,
    textAlign: 'center',
    marginBottom: ms(10),
  },
  emptyEventOr: {
    color: colors.grayDarker,
    fontSize: fontSizes.sm,
    textAlign: 'center',
    marginBottom: ms(10),
  },
  suggestedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: ms(10),
  },
});
